### ISSUE TITLE
I don't understand the most recent change

### ISSUE THREAD

**Issue by dkassen** [dpep/rspec-uuid#41]
..seems like this gem was blown up (commit message "boom")? Where's the matcher for UUIDs? Also the description makes no sense with the gem name.

**Comment by dpep** [comment]
omg epic fail on my part  🤦🏻 (copy/pasta while bootstrapping a new repo)   git history restored, thanks for catching this @dkassen !

if you don't mind me asking - how did you catch this so quick?!  are you using the gem and if so how is it serving you?

**Comment by dpep** [comment]
glad to be of service simplifying codebases!  yeah, I wrote this gem to replace a bunch of regexes...

reach out anytime!

**Comment by dpep** [comment]
and if you wouldn't mind, please consider [donating a star](https://github.com/dpep/rspec-uuid/stargazers)  🙏🏻
